/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Anadir;

import com.mycompany.proyectosockets.CRUDSockets;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Anadir extends javax.swing.JDialog {

    private ArrayList<JTextField> data = new ArrayList<>();
    private ArrayList<String> string = new ArrayList<>();

    /**
     * Creates new form Anadir
     */
    public Anadir(java.awt.Frame parent, boolean modal) throws SQLException {
        
        super(parent, modal);
        initComponents();
        
        CRUDSockets c = new CRUDSockets();
        
        this.setLocationRelativeTo(c);
        
        Connection con = c.iniciarConexion();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("Select * from " + c.mandar + " ");
        ResultSetMetaData rsmd = rs.getMetaData();

        jLabelTitulo.setText("Añadir " + c.mandar + " ");

        this.setLayout(new FlowLayout());
        jPanelAnadir.setLayout(new GridBagLayout());

        jPanelAnadir.add(jLabelTitulo, createGbc(1, 0));
        jPanelAnadir.add(jButton1, createGbc(1, 8));

        for (int i = 0; i < rsmd.getColumnCount(); i++) {
            JTextField jt = new JTextField();
            JLabel jl = new JLabel("Introduce " + rsmd.getColumnName(i + 1) + " ");
            jPanelAnadir.add(jl, createGbc(0, i + 1));
            jt.setPreferredSize(new Dimension(200, 30));
            jPanelAnadir.add(jt, createGbc(1, i + 1));
            jPanelAnadir.setVisible(true);
            data.add(jt);
        }
    }

    private GridBagConstraints createGbc(int x, int y) {
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = x;
        gbc.gridy = y;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1.0;
        gbc.weighty = 0.0;

        gbc.insets = new Insets(2, 2, 2, 2);

        gbc.anchor = x % 2 == 0 ? GridBagConstraints.WEST : GridBagConstraints.EAST;
        return gbc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAnadir = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitulo.setText("jLabel1");

        javax.swing.GroupLayout jPanelAnadirLayout = new javax.swing.GroupLayout(jPanelAnadir);
        jPanelAnadir.setLayout(jPanelAnadirLayout);
        jPanelAnadirLayout.setHorizontalGroup(
            jPanelAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnadirLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelAnadirLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelAnadirLayout.setVerticalGroup(
            jPanelAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnadirLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanelAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanelAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            // TODO add your handling code here:
            CRUDSockets c = new CRUDSockets();

            Connection con = c.iniciarConexion();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * from " + c.mandar + " ");
            ResultSetMetaData rsmd = rs.getMetaData();

            for (JTextField jTextField : data) {
                String nuevo = jTextField.getText();
                string.add(nuevo);
            }

            // Creo la consulta para poder meter cualquier número de datos
            StringBuilder sql = new StringBuilder("INSERT INTO " + c.mandar + " VALUES ( '" + string.get(0) + "' ");
            for (int i = 1; i <= string.size() - 1; i++) {
                sql.append(", '" + string.get(i) + "' ");
            }
            sql.append(")");

            st.executeUpdate(sql.toString());
            
            
            JOptionPane.showMessageDialog(this, "El registro se insertó con éxito", "Insertado con éxito", JOptionPane.DEFAULT_OPTION);

            this.setVisible(false);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "ERROR", JOptionPane.WARNING_MESSAGE);
            Logger.getLogger(Anadir.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Anadir dialog = new Anadir(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Anadir.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelAnadir;
    // End of variables declaration//GEN-END:variables
}
